package Persistencia;

import lombok.*;

@Setter
@Getter
public class BuildDeTabelas extends ConexaoComOBancoDeDados {

    private final String tabelaPerfil = "CREATE TABLE IF NOT EXISTS PERFIL ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "NOME VARCHAR(50) NOT NULL, "
            + "ATIVO BOOLEAN NOT NULL, "
            + "DATA_CADASTRO DATE NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaEstado = "CREATE TABLE IF NOT EXISTS ESTADO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "DESCRICAO VARCHAR(40) NOT NULL, "
            + "SIGLA VARCHAR(2) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaCidade = "CREATE TABLE IF NOT EXISTS CIDADE ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "DESCRICAO VARCHAR(50) NOT NULL, "
            + "IDENTIFICADOR_ESTADO INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY (IDENTIFICADOR_ESTADO) REFERENCES "
            + "ESTADO(IDENTIFICADOR));";

    private final String tabelaBairro = "CREATE TABLE IF NOT EXISTS BAIRRO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "IDENTIFICADOR_CIDADE INTEGER, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_CIDADE) REFERENCES "
            + "CIDADE (IDENTIFICADOR));";

    private final String tabelaLogradouro = "CREATE TABLE IF NOT EXISTS LOGRADOURO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "IDENTIFICADOR_BAIRRO INTEGER, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_BAIRRO) REFERENCES "
            + "LOGRADOURO (IDENTIFICADOR));";

    private final String tabelaCep = "CREATE TABLE IF NOT EXISTS CEP ( "
            + "CEP INTEGER NOT NULL, "
            + "IDENTIFICADOR_LOGRADOURO INTEGER NOT NULL, "
            + "PRIMARY KEY (CEP), "
            + "FOREIGN KEY (IDENTIFICADOR_LOGRADOURO) REFERENCES LOGRADOURO(IDENTIFICADOR)"
            + ");";

    private final String tabelaTipoEndereco = "CREATE TABLE IF NOT EXISTS TIPO_ENDERECO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS "
            + "IDENTITY(START WITH 100, INCREMENT BY 1), "
            + "DESCRICAO VARCHAR(20) NOT NULL,  "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaEndereco = "CREATE TABLE IF NOT EXISTS ENDERECO ( "
            + "IDENTIFICADOR INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1) NOT NULL, "
            + "CEP_CEP INTEGER NOT NULL, "
            + "COMPLEMENTO VARCHAR(100) NOT NULL, "
            + "NUMERO INTEGER NOT NULL, "
            + "IDENTIFICADOR_TIPO_ENDERECO INTEGER NOT NULL, "
            + "PONTO_DE_REFERENCIA VARCHAR(100) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(IDENTIFICADOR), "
            + "FOREIGN KEY(CEP_CEP) REFERENCES CEP(CEP));";

    private final String insertDadosTbEstado = ""
            + "INSERT INTO ESTADO(DESCRICAO,SIGLA) VALUES "
            + "('DISTRITO FEDERAL','DF'), "
            + "('MINAS GERAIS','MG'),"
            + "('SÃO PAULO','SP'),"
            + "('RIO DE JANEIRO','RJ'),"
            + "('BAHIA','BA'),"
            + "('PARAÍBA','PB');";
    
    private final String insertDadosIniciaisPerfil = ""
            + "INSERT INTO PERFIL (NOME,ATIVO,DATA_CADASTRO) VALUES "
            + "('ADMINISTRADOR',TRUE,CURRENT_DATE),"
            + "('USUÁRIO',TRUE,CURRENT_DATE),"
            + "('USUÁRIO_AVANÇADO',TRUE,CURRENT_DATE);";

    private final String inserirDadosIniciaisEmEstado = ""
            + "INSERT INTO ESTAFO(DESCRICAO,SIGLA) VALUES "
            + "('SÃO PAULO','SP'),"
            + "('PARAÍBA','PB'),"
            + "('MARANHÃO','MA'),"
            + "('PIAUÍ','PI'),"
            + "('RIO DE JANEIRO','RJ'),"
            + "('RIO GRANDE DO SUL','RS'),"
            + "('RIO GRANDE DO NORTE','RN'),"
            + "('GOIÁS','GO'),"
            + "('AMAZONAS','AM'),"
            + "('ACRE','AC'),"
            + "('MATO GROSSO','MT'),"
            + "('PARANÁ', 'PR'),"
            + "('ALAGOAS','AL'),"
            + "('TOCANTINS','TO'),"
            + "('RORAIMA','RR'),"
            + "('CEARÁ','CE'),"
            + "('RONDÔNIA','RO'),"
            + "('PARÁ','PA'),"
            + "('ESPIRITO SANTO','ES'),"
            + "('BAHIA','BA'),"
            + "('SERGIPE','SE'),"
            + "('PERNAMBUCO',PE''),"
            + "('AMAPÁ','AP'),"
            + "('DISTRITO FEDERAL','DF'),"
            + "('MATO GROSSO DO SUL','MS'),"
            + "('MINAS GERAIS','MG'),"
            + "('SANTA CATARINA','SC'),";
    
    public void construirTabelas() {

        executarComandoSql(tabelaPerfil);
        executarComandoSql(tabelaEstado);
        executarComandoSql(tabelaCidade);
        executarComandoSql(tabelaBairro);
        executarComandoSql(tabelaLogradouro);
        executarComandoSql(tabelaCep);
        executarComandoSql(tabelaTipoEndereco);
        executarComandoSql(tabelaEndereco);

    }
    
    public void inserirDadosIniciais(){
        
        if(isTabelaVazia("PERFIL")){  
            
        executarComandoSql(insertDadosIniciaisPerfil);
        
        }          
    }

}
